[redis]
    dbName = "beats"
    dbIndex = 1
    addr = ["127.0.0.1:6379"]
    deployMode = "node"
    minIdleConns = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    slowOpTimeout = "100ms"

[log]
    name = "run.log"
    dir = "."
    addCaller = true
    level = "debug"
    callerSkip = 1
    flushInterval= "1s"
    debug = true
    enableAsyncLog = false
    disableStacktrace = false
    maxSize = 500 # maximum 500M log size
    maxAge = 30 # retain maximum 30 days
    maxBackup = 100 # retian maximum 100 log
    watchConfig = true

[es]
    urls = ["http://localhost:9200"]